// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Learn SQL",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Learn SQL",
            targets: ["AppModule"],
            bundleIdentifier: "com.jansari.rishi.SQL-Activity",
            teamIdentifier: "WGJA24P7XU",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/tevelee/SwiftUI-Flow", "3.1.1"..<"4.0.0"),
        .package(url: "https://github.com/simibac/ConfettiSwiftUI", "3.0.0"..<"4.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Flow", package: "swiftui-flow"),
                .product(name: "ConfettiSwiftUI", package: "confettiswiftui")
            ],
            path: "."
        )
    ]
)