// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SQL Activity",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "SQL Activity",
            targets: ["AppModule"],
            bundleIdentifier: "com.jansari.rishi.SQL-Activity",
            teamIdentifier: "WGJA24P7XU",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .tv),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/tevelee/SwiftUI-Flow", "3.1.1"..<"4.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Flow", package: "swiftui-flow")
            ],
            path: "."
        )
    ]
)